### ISSUE TITLE
Some issue i found while using the latest build in 2 days

### ISSUE THREAD

**Issue by Dezato108** [SissioMisio/android_device_realme_cupidr#1]
1. Detect phone in pocket mode: sometimes it detects wrong state of the phone while lying straight on the table it still detect as in pocket
2. Auto brightness: Currently when turn this on, the screen hit 100% brightness
3. Charging speed on lockscreen: Currently shows 0mA 0W, i don't know if it receive full 60W charger at 0% battery or not
4. Just a little add-on: Can you include the options to hide battery icon in the status bar? it'll be much cleaner if it only shows battery percentage in text

Btw great build, i'm comfortable using this as my daily driver. Very excited for your next build!

**Comment by SissioMisio** [comment]
1. Weird... I've never faced this issue. It could be cause entirely by the proximity sensor; check if something is obstructing it.
2. Again, I've never faced this issue. It could be that you're in a dark environment and the light sensor captures the light of the screen and turns up the brightness (RealmeUI probably used another method to auto adjust brightness... we'll look into it).
3. This bug will be fixed in the next build (and yes, Superdart charging should work in the next build).
4. I think this was removed in the EvolutionX sources... I swear the setting was present...

The last build (3rd) is a little outdated, so a lot of bugs are fixed in the 7.9.5 EvolutionX version.
I'm trying to compile a new build based on the latest sources right now, when I succeed I'll try and fix the 4th point!


Thanks for reporting! ;)
If you have any other problems feel free to send them here!

**Comment by SissioMisio** [comment]
New build is out! Try it out!! @Dezato108

**Comment by Dezato108** [comment]
> New build is out! Try it out!! @Dezato108

sure, i will try it tonight. Can i dirty flash over the old build ?

**Comment by SissioMisio** [comment]
> > New build is out! Try it out!! @Dezato108
> 
> sure, i will try it tonight. Can i dirty flash over the old build ?

No, you'll need to do a clean install.
