### ISSUE TITLE
Bug log for build tq3c.230705.001.c2-07262045

### ISSUE THREAD

**Issue by Dezato108** [SissioMisio/android_device_realme_cupidr#2]
1- All the previous issue from last build is solve -> Great!
2- Some new bug:
- Estimate time till full charge on the lock screen isn't correct. I charge the phone at 20% and the lock screen shows superDart charging, but the time always shows 20 mins to full charge, even at 90% battery
- When bluethooth device connect for the first time, it wont receive the signal. I tried with some devices i have: Cosair HS65 wireless, Klipsh T5, PS5 Dualsense Controller
- Sometimes, video playback will get glitched and dont have sound. This problems appear on facebook, youtube, messenger, chrome,.. (every video playback app i tested have the same result). 
2 last bug disappear when restart the phone, but randomly appear again. I use the phone for media playback a lot, so i cant use this rom version due to those issues.

**Comment by SissioMisio** [comment]
Hi, thank you for reaching out to me!

• I don't have that estimated charge issue... It works fine for me. Maybe it's an EvolutionX bug (not related to my build);

• I've never faced any problem with Bluetooth. I use Bluetooth earbuds everyday and they work flawlessly;

• Again, I don't have this issue. I watch YouTube, Instagram, Whatsapp, ... videos everyday and never had a problem.


You could try clean-installing the rom to fix those bugs, because I don't have any of them...

**Comment by miguelthemann** [comment]
Okay, I'm no one to talk, but I've had similar issues because of the firmware. Did you flash the F.12 firmware on both slots?

**Comment by Dezato108** [comment]
> Okay, I'm no one to talk, but I've had similar issues because of the firmware. Did you flash the F.12 firmware on both slots?

i havent, i'll try it another time tho

**Comment by miguelthemann** [comment]
> i havent, i'll try it another time tho

Alright. Wish you the best of luck. If you need any further help, feel free to drop it here!

**Comment by SissioMisio** [comment]
Closing the issue as completed for inactivity (and because that was an old build)

**Comment by miguelthemann** [comment]
Jumpscare-sissio.comment

**Comment by SissioMisio** [comment]
> Jumpscare-sissio.comment

😳
